# Generated by Django 3.1 on 2020-08-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='pcreated_by',
        ),
    ]
